# Generated by Django 3.2 on 2023-12-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('rle_title', models.CharField(max_length=255)),
                ('rle_desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
    ]
